//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoExpensesEntity
{
    using System;
    using System.Collections.Generic;
    
    //public partial class Category
    //{
    //    public Category()
    //    {
    //        this.Tasks = new HashSet<Task>();
    //    }
    
    //    public int CategoryID { get; set; }
    //    public string CategoryTitle { get; set; }
    //    public int CategoryStatus { get; set; }
    //    public System.DateTime CreatedDate { get; set; }
    //    public Nullable<int> UserID { get; set; }
    
    //    public virtual ICollection<Task> Tasks { get; set; }
    //    public virtual UserDetail UserDetail { get; set; }
    //}
}
