//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoExpensesEntity
{
    using System;
    using System.Collections.Generic;
    
    //public partial class CompletedTask
    //{
    //    public int CompletedTaskID { get; set; }
    //    public int TaskID { get; set; }
    //    public Nullable<System.DateTime> CompletedDate { get; set; }
    //    public Nullable<System.DateTime> SheduledDate { get; set; }
    //    public Nullable<int> DifferenceMargin { get; set; }
    //    public Nullable<System.DateTime> CreateDate { get; set; }
    //    public Nullable<decimal> Expence { get; set; }
    //    public Nullable<int> UserID { get; set; }
    
    //    public virtual Task Task { get; set; }
    //    public virtual UserDetail UserDetail { get; set; }
    //}
}
