//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoExpenceses.DoExpensesEntity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using DoExpenceses.DoExpensesDto;
    public partial class DoExpencesesAngualarEntitiesConnection : DbContext
    {
        public DoExpencesesAngualarEntitiesConnection()
            : base("name=DoExpencesesAngualarEntitiesConnection")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Category> Categories { get; set; }
        public DbSet<CompletedTask> CompletedTasks { get; set; }
        public DbSet<Task> Tasks { get; set; }
        public DbSet<UserDetail> UserDetails { get; set; }
    }
}
