//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoExpensesEntity
{
    using System;
    using System.Collections.Generic;
    
    //public partial class Task
    //{
    //    public Task()
    //    {
    //        this.CompletedTasks = new HashSet<CompletedTask>();
    //    }
    
    //    public int TaskID { get; set; }
    //    public int CategoryID { get; set; }
    //    public string Description { get; set; }
    //    public Nullable<System.DateTime> SheduledDate { get; set; }
    //    public string RecuringType { get; set; }
    //    public Nullable<decimal> Expence { get; set; }
    //    public int TaskStatus { get; set; }
    //    public Nullable<int> UserID { get; set; }
    
    //    public virtual Category Category { get; set; }
    //    public virtual ICollection<CompletedTask> CompletedTasks { get; set; }
    //    public virtual UserDetail UserDetail { get; set; }
    //}
}
