//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoExpensesEntity
{
    using System;
    using System.Collections.Generic;
    
    //public partial class UserDetail
    //{
    //    public UserDetail()
    //    {
    //        this.Categories = new HashSet<Category>();
    //        this.CompletedTasks = new HashSet<CompletedTask>();
    //        this.Tasks = new HashSet<Task>();
    //    }
    
    //    public int UserID { get; set; }
    //    public string UserName { get; set; }
    //    public string Password { get; set; }
    //    public string FirstName { get; set; }
    //    public string LastName { get; set; }
    //    public string EmaillID { get; set; }
    //    public int Status { get; set; }
    //    public System.DateTime CreateDate { get; set; }
    
    //    public virtual ICollection<Category> Categories { get; set; }
    //    public virtual ICollection<CompletedTask> CompletedTasks { get; set; }
    //    public virtual ICollection<Task> Tasks { get; set; }
    //}
}
